# Generated by Django 6.0.3 on 2026-05-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customeruser_avatar_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='resume_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='resume_genres',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Жанры съемки'),
        ),
    ]
