# Generated by Django 6.0.3 on 2026-05-30 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customeruser_resume_city_customeruser_resume_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('genre', models.CharField(choices=[('portrait', 'Портрет'), ('landscape', 'Пейзаж'), ('interior', 'Интерьер'), ('reportage', 'Репортаж')], default='portrait', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_photo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
