# Generated by Django 6.0.3 on 2026-05-30 20:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_portfoliophoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliophoto',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='portfoliophoto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfoliophoto',
            name='image',
            field=models.ImageField(upload_to='portfolio_photos/'),
        ),
        migrations.AlterField(
            model_name='portfoliophoto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
